package ent;
// Generated Jul 2, 2013 11:18:19 PM by Hibernate Tools 3.2.1.GA



/**
 * BloodTest generated by hbm2java
 */
public class BloodTest  implements java.io.Serializable {


     private Integer siNo;
     private String regid;
     private String testDate;
     private String hemoglobin;
     private String tlc;
     private String neutrofill;
     private String lymphocytes;
     private String monocytes;
     private String basophils;
     private String othercount;
     private String totalRbc;
     private String platlets;
     private String bloodGroup;

    public BloodTest() {
    }

    public BloodTest(String regid, String testDate, String hemoglobin, String tlc, String neutrofill, String lymphocytes, String monocytes, String basophils, String othercount, String totalRbc, String platlets, String bloodGroup) {
       this.regid = regid;
       this.testDate = testDate;
       this.hemoglobin = hemoglobin;
       this.tlc = tlc;
       this.neutrofill = neutrofill;
       this.lymphocytes = lymphocytes;
       this.monocytes = monocytes;
       this.basophils = basophils;
       this.othercount = othercount;
       this.totalRbc = totalRbc;
       this.platlets = platlets;
       this.bloodGroup = bloodGroup;
    }
   
    public Integer getSiNo() {
        return this.siNo;
    }
    
    public void setSiNo(Integer siNo) {
        this.siNo = siNo;
    }
    public String getRegid() {
        return this.regid;
    }
    
    public void setRegid(String regid) {
        this.regid = regid;
    }
    public String getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(String testDate) {
        this.testDate = testDate;
    }
    public String getHemoglobin() {
        return this.hemoglobin;
    }
    
    public void setHemoglobin(String hemoglobin) {
        this.hemoglobin = hemoglobin;
    }
    public String getTlc() {
        return this.tlc;
    }
    
    public void setTlc(String tlc) {
        this.tlc = tlc;
    }
    public String getNeutrofill() {
        return this.neutrofill;
    }
    
    public void setNeutrofill(String neutrofill) {
        this.neutrofill = neutrofill;
    }
    public String getLymphocytes() {
        return this.lymphocytes;
    }
    
    public void setLymphocytes(String lymphocytes) {
        this.lymphocytes = lymphocytes;
    }
    public String getMonocytes() {
        return this.monocytes;
    }
    
    public void setMonocytes(String monocytes) {
        this.monocytes = monocytes;
    }
    public String getBasophils() {
        return this.basophils;
    }
    
    public void setBasophils(String basophils) {
        this.basophils = basophils;
    }
    public String getOthercount() {
        return this.othercount;
    }
    
    public void setOthercount(String othercount) {
        this.othercount = othercount;
    }
    public String getTotalRbc() {
        return this.totalRbc;
    }
    
    public void setTotalRbc(String totalRbc) {
        this.totalRbc = totalRbc;
    }
    public String getPlatlets() {
        return this.platlets;
    }
    
    public void setPlatlets(String platlets) {
        this.platlets = platlets;
    }
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }




}


