package ent;
// Generated Jul 2, 2013 11:18:19 PM by Hibernate Tools 3.2.1.GA



/**
 * Booking generated by hbm2java
 */
public class Booking  implements java.io.Serializable {


     private Integer token;
     private String name;
     private String date;
     private String time;
     private String doctor;

    public Booking() {
    }

    public Booking(String name, String date, String time, String doctor) {
       this.name = name;
       this.date = date;
       this.time = time;
       this.doctor = doctor;
    }
   
    public Integer getToken() {
        return this.token;
    }
    
    public void setToken(Integer token) {
        this.token = token;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(String doctor) {
        this.doctor = doctor;
    }




}


