package ent;
// Generated Jul 2, 2013 11:18:19 PM by Hibernate Tools 3.2.1.GA



/**
 * DoctorDiaganosis generated by hbm2java
 */
public class DoctorDiaganosis  implements java.io.Serializable {


     private Integer siNo;
     private Integer regId;
     private String consultDate;
     private String remark;
     private String blood;
     private String xray;
     private String scan;
     private String reconsultWeek;
     private String reconsultAdviceDate;
     private String finalConsult;

    public DoctorDiaganosis() {
    }

    public DoctorDiaganosis(Integer regId, String consultDate, String remark, String blood, String xray, String scan, String reconsultWeek, String reconsultAdviceDate, String finalConsult) {
       this.regId = regId;
       this.consultDate = consultDate;
       this.remark = remark;
       this.blood = blood;
       this.xray = xray;
       this.scan = scan;
       this.reconsultWeek = reconsultWeek;
       this.reconsultAdviceDate = reconsultAdviceDate;
       this.finalConsult = finalConsult;
    }
   
    public Integer getSiNo() {
        return this.siNo;
    }
    
    public void setSiNo(Integer siNo) {
        this.siNo = siNo;
    }
    public Integer getRegId() {
        return this.regId;
    }
    
    public void setRegId(Integer regId) {
        this.regId = regId;
    }
    public String getConsultDate() {
        return this.consultDate;
    }
    
    public void setConsultDate(String consultDate) {
        this.consultDate = consultDate;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public String getBlood() {
        return this.blood;
    }
    
    public void setBlood(String blood) {
        this.blood = blood;
    }
    public String getXray() {
        return this.xray;
    }
    
    public void setXray(String xray) {
        this.xray = xray;
    }
    public String getScan() {
        return this.scan;
    }
    
    public void setScan(String scan) {
        this.scan = scan;
    }
    public String getReconsultWeek() {
        return this.reconsultWeek;
    }
    
    public void setReconsultWeek(String reconsultWeek) {
        this.reconsultWeek = reconsultWeek;
    }
    public String getReconsultAdviceDate() {
        return this.reconsultAdviceDate;
    }
    
    public void setReconsultAdviceDate(String reconsultAdviceDate) {
        this.reconsultAdviceDate = reconsultAdviceDate;
    }
    public String getFinalConsult() {
        return this.finalConsult;
    }
    
    public void setFinalConsult(String finalConsult) {
        this.finalConsult = finalConsult;
    }




}


