package ent;
// Generated Jul 2, 2013 11:18:19 PM by Hibernate Tools 3.2.1.GA



/**
 * Reg generated by hbm2java
 */
public class Reg  implements java.io.Serializable {


     private Integer siNo;
     private String fname;
     private String lname;
     private String religion;
     private String dob;
     private Integer age;
     private String sex;
     private String state;
     private String district;
     private String address;
     private String guardian;
     private String mob;
     private String email;

    public Reg() {
    }

    public Reg(String fname, String lname, String religion, String dob, Integer age, String sex, String state, String district, String address, String guardian, String mob, String email) {
       this.fname = fname;
       this.lname = lname;
       this.religion = religion;
       this.dob = dob;
       this.age = age;
       this.sex = sex;
       this.state = state;
       this.district = district;
       this.address = address;
       this.guardian = guardian;
       this.mob = mob;
       this.email = email;
    }
   
    public Integer getSiNo() {
        return this.siNo;
    }
    
    public void setSiNo(Integer siNo) {
        this.siNo = siNo;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getGuardian() {
        return this.guardian;
    }
    
    public void setGuardian(String guardian) {
        this.guardian = guardian;
    }
    public String getMob() {
        return this.mob;
    }
    
    public void setMob(String mob) {
        this.mob = mob;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


