package ent;
// Generated Jul 2, 2013 11:18:19 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer count;
     private BigDecimal prize;

    public Transaction() {
    }

    public Transaction(String name, Integer count, BigDecimal prize) {
       this.name = name;
       this.count = count;
       this.prize = prize;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public BigDecimal getPrize() {
        return this.prize;
    }
    
    public void setPrize(BigDecimal prize) {
        this.prize = prize;
    }




}


