package ent;
// Generated Jul 2, 2013 11:18:19 PM by Hibernate Tools 3.2.1.GA



/**
 * XrayTest generated by hbm2java
 */
public class XrayTest  implements java.io.Serializable {


     private Integer siNo;
     private Integer regId;
     private String testDate;
     private String remark1;
     private String remark2;
     private String remark3;
     private String remark4;
     private String remark5;
     private String opinion;

    public XrayTest() {
    }

    public XrayTest(Integer regId, String testDate, String remark1, String remark2, String remark3, String remark4, String remark5, String opinion) {
       this.regId = regId;
       this.testDate = testDate;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.remark3 = remark3;
       this.remark4 = remark4;
       this.remark5 = remark5;
       this.opinion = opinion;
    }
   
    public Integer getSiNo() {
        return this.siNo;
    }
    
    public void setSiNo(Integer siNo) {
        this.siNo = siNo;
    }
    public Integer getRegId() {
        return this.regId;
    }
    
    public void setRegId(Integer regId) {
        this.regId = regId;
    }
    public String getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(String testDate) {
        this.testDate = testDate;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public String getRemark3() {
        return this.remark3;
    }
    
    public void setRemark3(String remark3) {
        this.remark3 = remark3;
    }
    public String getRemark4() {
        return this.remark4;
    }
    
    public void setRemark4(String remark4) {
        this.remark4 = remark4;
    }
    public String getRemark5() {
        return this.remark5;
    }
    
    public void setRemark5(String remark5) {
        this.remark5 = remark5;
    }
    public String getOpinion() {
        return this.opinion;
    }
    
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }




}


