package voting;
// Generated Apr 5, 2013 12:53:13 PM by Hibernate Tools 3.2.1.GA



/**
 * CandidateReg generated by hbm2java
 */
public class CandidateReg  implements java.io.Serializable {


     private Integer siNo;
     private Integer userId;
     private String name;
     private String department;
     private String party;
     private String nominee;

    public CandidateReg() {
    }

    public CandidateReg(Integer userId, String name, String department, String party, String nominee) {
       this.userId = userId;
       this.name = name;
       this.department = department;
       this.party = party;
       this.nominee = nominee;
    }
   
    public Integer getSiNo() {
        return this.siNo;
    }
    
    public void setSiNo(Integer siNo) {
        this.siNo = siNo;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getParty() {
        return this.party;
    }
    
    public void setParty(String party) {
        this.party = party;
    }
    public String getNominee() {
        return this.nominee;
    }
    
    public void setNominee(String nominee) {
        this.nominee = nominee;
    }




}


