package voting;
// Generated Apr 5, 2013 12:53:13 PM by Hibernate Tools 3.2.1.GA



/**
 * VoterReg generated by hbm2java
 */
public class VoterReg  implements java.io.Serializable {


     private Integer siNo;
     private String name;
     private String gender;
     private String dob;
     private String address;
     private String email;
     private String department;
     private String studyPeriod;
     private String userName;
     private String pass;

    public VoterReg() {
    }

    public VoterReg(String name, String gender, String dob, String address, String email, String department, String studyPeriod, String userName, String pass) {
       this.name = name;
       this.gender = gender;
       this.dob = dob;
       this.address = address;
       this.email = email;
       this.department = department;
       this.studyPeriod = studyPeriod;
       this.userName = userName;
       this.pass = pass;
    }
   
    public Integer getSiNo() {
        return this.siNo;
    }
    
    public void setSiNo(Integer siNo) {
        this.siNo = siNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getStudyPeriod() {
        return this.studyPeriod;
    }
    
    public void setStudyPeriod(String studyPeriod) {
        this.studyPeriod = studyPeriod;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


