package db;
// Generated Jul 2, 2013 2:58:38 PM by Hibernate Tools 3.2.1.GA



/**
 * Biddder generated by hbm2java
 */
public class Biddder  implements java.io.Serializable {


     private Integer bidderid;
     private Addtender addtender;
     private Double bidprice;
     private Integer yofex;
     private String nameofbank;
     private String acNo;
     private Integer siNo;

    public Biddder() {
    }

    public Biddder(Addtender addtender, Double bidprice, Integer yofex, String nameofbank, String acNo, Integer siNo) {
       this.addtender = addtender;
       this.bidprice = bidprice;
       this.yofex = yofex;
       this.nameofbank = nameofbank;
       this.acNo = acNo;
       this.siNo = siNo;
    }
   
    public Integer getBidderid() {
        return this.bidderid;
    }
    
    public void setBidderid(Integer bidderid) {
        this.bidderid = bidderid;
    }
    public Addtender getAddtender() {
        return this.addtender;
    }
    
    public void setAddtender(Addtender addtender) {
        this.addtender = addtender;
    }
    public Double getBidprice() {
        return this.bidprice;
    }
    
    public void setBidprice(Double bidprice) {
        this.bidprice = bidprice;
    }
    public Integer getYofex() {
        return this.yofex;
    }
    
    public void setYofex(Integer yofex) {
        this.yofex = yofex;
    }
    public String getNameofbank() {
        return this.nameofbank;
    }
    
    public void setNameofbank(String nameofbank) {
        this.nameofbank = nameofbank;
    }
    public String getAcNo() {
        return this.acNo;
    }
    
    public void setAcNo(String acNo) {
        this.acNo = acNo;
    }
    public Integer getSiNo() {
        return this.siNo;
    }
    
    public void setSiNo(Integer siNo) {
        this.siNo = siNo;
    }




}


