package db;
// Generated Jul 2, 2013 2:58:38 PM by Hibernate Tools 3.2.1.GA



/**
 * Vendor generated by hbm2java
 */
public class Vendor  implements java.io.Serializable {


     private Integer siNo;
     private String companyName;
     private String userName;
     private String pass;
     private String email;
     private String website;
     private String address;
     private String landPhone;
     private String mobile;

    public Vendor() {
    }

    public Vendor(String companyName, String userName, String pass, String email, String website, String address, String landPhone, String mobile) {
       this.companyName = companyName;
       this.userName = userName;
       this.pass = pass;
       this.email = email;
       this.website = website;
       this.address = address;
       this.landPhone = landPhone;
       this.mobile = mobile;
    }
   
    public Integer getSiNo() {
        return this.siNo;
    }
    
    public void setSiNo(Integer siNo) {
        this.siNo = siNo;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getLandPhone() {
        return this.landPhone;
    }
    
    public void setLandPhone(String landPhone) {
        this.landPhone = landPhone;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


