package db;
// Generated May 26, 2013 11:34:48 PM by Hibernate Tools 3.2.1.GA



/**
 * Bidder generated by hbm2java
 */
public class Bidder  implements java.io.Serializable {


     private Integer bidderid;
     private Addtender addtender;
     private Vendor vendor;
     private double bidprice;
     private int yofex;
     private String nameofbank;
     private String acNo;

    public Bidder() {
    }

    public Bidder(Addtender addtender, Vendor vendor, double bidprice, int yofex, String nameofbank, String acNo) {
       this.addtender = addtender;
       this.vendor = vendor;
       this.bidprice = bidprice;
       this.yofex = yofex;
       this.nameofbank = nameofbank;
       this.acNo = acNo;
    }
   
    public Integer getBidderid() {
        return this.bidderid;
    }
    
    public void setBidderid(Integer bidderid) {
        this.bidderid = bidderid;
    }
    public Addtender getAddtender() {
        return this.addtender;
    }
    
    public void setAddtender(Addtender addtender) {
        this.addtender = addtender;
    }
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }
    public double getBidprice() {
        return this.bidprice;
    }
    
    public void setBidprice(double bidprice) {
        this.bidprice = bidprice;
    }
    public int getYofex() {
        return this.yofex;
    }
    
    public void setYofex(int yofex) {
        this.yofex = yofex;
    }
    public String getNameofbank() {
        return this.nameofbank;
    }
    
    public void setNameofbank(String nameofbank) {
        this.nameofbank = nameofbank;
    }
    public String getAcNo() {
        return this.acNo;
    }
    
    public void setAcNo(String acNo) {
        this.acNo = acNo;
    }




}


