/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPhoneBook.java
 *
 * Created on Sep 26, 2011, 1:20:02 AM
 */
package phonebook;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class frmPhoneBook extends javax.swing.JFrame  {
ResultSet rs=null;
Connection con=null;
 
Statement stmt=null;
  public static frmPhoneBook frame = new frmPhoneBook();
    
    /** Creates new form frmPhoneBook */
  
 
    public frmPhoneBook() {
        initComponents();
        center();
       
    
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        txtgen = new javax.swing.JComboBox();
        txtlang = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        txtpay1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbtadd = new javax.swing.JButton();
        jbtdelete = new javax.swing.JButton();
        jbtsearch = new javax.swing.JButton();
        jbtexit = new javax.swing.JButton();
        jbtclear = new javax.swing.JButton();
        jbtback = new javax.swing.JButton();
        jbtupdate = new javax.swing.JButton();
        jbtfirst = new javax.swing.JButton();
        jbtPrevious = new javax.swing.JButton();
        jbtnext = new javax.swing.JButton();
        jbtlast = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Age :");

        jLabel1.setText("Customer ID :");

        jLabel2.setText("Customer Name:");

        jLabel4.setText("Address :");

        jLabel5.setText("Gender:");

        jLabel6.setText("Program Language:");

        jLabel7.setText("Customer No: ");

        jLabel9.setText("Payment  :");

        txtid.setText(" ");

        txtname.setText(" ");

        txtage.setText(" ");

        txtadd.setColumns(20);
        txtadd.setRows(5);
        jScrollPane1.setViewportView(txtadd);

        txtgen.setEditable(true);
        txtgen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        txtlang.setText(" ");

        txtnum.setText(" ");

        txtpay1.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpay1)
                    .addComponent(txtlang)
                    .addComponent(txtgen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addComponent(txtage)
                    .addComponent(txtname)
                    .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txtnum, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtlang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtpay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Phone Book ");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);

        jbtadd.setBackground(new java.awt.Color(102, 255, 102));
        jbtadd.setText("Add");
        jbtadd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtaddMouseMoved(evt);
            }
        });
        jbtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtaddActionPerformed(evt);
            }
        });

        jbtdelete.setBackground(new java.awt.Color(102, 255, 102));
        jbtdelete.setText("Delete");
        jbtdelete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtdeleteMouseMoved(evt);
            }
        });
        jbtdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdeleteActionPerformed(evt);
            }
        });

        jbtsearch.setBackground(new java.awt.Color(102, 255, 102));
        jbtsearch.setText("Search");
        jbtsearch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtsearchMouseMoved(evt);
            }
        });
        jbtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsearchActionPerformed(evt);
            }
        });

        jbtexit.setBackground(new java.awt.Color(102, 255, 102));
        jbtexit.setText("Exit");
        jbtexit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtexitMouseMoved(evt);
            }
        });
        jbtexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtexitActionPerformed(evt);
            }
        });

        jbtclear.setBackground(new java.awt.Color(102, 255, 102));
        jbtclear.setText("Clear");
        jbtclear.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtclearMouseMoved(evt);
            }
        });
        jbtclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtclearActionPerformed(evt);
            }
        });

        jbtback.setBackground(new java.awt.Color(102, 255, 102));
        jbtback.setText("Back");
        jbtback.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtbackMouseMoved(evt);
            }
        });
        jbtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbackActionPerformed(evt);
            }
        });

        jbtupdate.setText("Update");
        jbtupdate.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtupdateMouseMoved(evt);
            }
        });
        jbtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtupdateActionPerformed(evt);
            }
        });

        jbtfirst.setText("First");
        jbtfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtfirstActionPerformed(evt);
            }
        });

        jbtPrevious.setText("Previous");
        jbtPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPreviousActionPerformed(evt);
            }
        });

        jbtnext.setText("Next");
        jbtnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnextActionPerformed(evt);
            }
        });

        jbtlast.setText("Last");
        jbtlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlastActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnext, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtlast, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtback, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jbtexit, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jbtclear, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jbtsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jbtdelete, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jbtadd, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jbtupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                .addContainerGap(26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jbtadd)
                        .addGap(18, 18, 18)
                        .addComponent(jbtdelete)
                        .addGap(18, 18, 18)
                        .addComponent(jbtsearch)
                        .addGap(18, 18, 18)
                        .addComponent(jbtupdate)
                        .addGap(18, 18, 18)
                        .addComponent(jbtclear)
                        .addGap(18, 18, 18)
                        .addComponent(jbtexit)
                        .addGap(18, 18, 18)
                        .addComponent(jbtback)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtfirst)
                    .addComponent(jbtPrevious)
                    .addComponent(jbtnext)
                    .addComponent(jbtlast))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtaddActionPerformed
        // TODO add your handling code here:
       try{
        DBconnection conn = new DBconnection();
                Connection connect = DBconnection.conn;
               Statement stmt = connect.createStatement();
stmt.executeUpdate("insert into data1 VALUES('"+txtid.getText()+"','"+txtname.getText()+"','"+txtage.getText()+"','"+txtadd.getText()+"','"+txtgen.getSelectedItem()+"','"+txtlang.getText()+"','"+txtnum.getText()+"','"+txtpay1.getText()+"')");
JOptionPane.showMessageDialog (null,"You successfully insert your records in your database!","Information Message",JOptionPane.INFORMATION_MESSAGE);
   connect.close();
//dbClose();
//dbOpen();

}catch(Exception e) {}
    }//GEN-LAST:event_jbtaddActionPerformed

    private void jbtdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdeleteActionPerformed
        // TODO add your handling code here:
        try{
            
          DBconnection conn = new DBconnection();
            Connection connect = DBconnection.conn;
             Statement stmt = connect.createStatement();
            stmt.executeUpdate("DELETE FROM data1 WHERE Id='"+ txtid.getText() +"'");
                connect.close();
          //dbClose();
         //   dbOpen();
            JOptionPane.showMessageDialog (null,"You successfully deleted the records of:  " +txtname.getText()+ "  in your database!","Information Message",JOptionPane.INFORMATION_MESSAGE);
            setText();
            }catch(Exception e){}
    
    }//GEN-LAST:event_jbtdeleteActionPerformed

    private void jbtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsearchActionPerformed
        // TODO add your handling code here:
        	try
		{
			 DBconnection conn = new DBconnection();
            Connection connect = DBconnection.conn;
            Statement stmt = connect.createStatement();
            
			rs = stmt.executeQuery("Select * from data1 WHERE id='"+txtid.getText()+"'");
                      
			if(rs.next())
			setText();
		}catch(Exception e){}
     



    }//GEN-LAST:event_jbtsearchActionPerformed

    private void jbtexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtexitActionPerformed
        // TODO add your handling code here:
        try{
if(JOptionPane.showConfirmDialog(null,"Are You Sure You Want to Return Main Menu?","Confirm",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
    setVisible(false); 
        new frmMainMenu().show();
            frmMainMenu frmMainMenu = new frmMainMenu();
}catch(Exception e){}
    }//GEN-LAST:event_jbtexitActionPerformed

    private void jbtclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtclearActionPerformed
        // TODO add your handling code here:
        try{
            txtid.setText("");
            txtname.setText("");
            txtage.setText("");
            txtadd.setText("");
            txtgen.setSelectedItem("");
            txtlang.setText("");
            txtnum.setText("");
            txtpay1.setText(""); 
        }catch(Exception e) {}
    }//GEN-LAST:event_jbtclearActionPerformed

    private void jbtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbackActionPerformed
        // TODO add your handling code here:
         setVisible(false);          
        new frmMainMenu().show();
        frmMainMenu frmMainMenu = new frmMainMenu();
    }//GEN-LAST:event_jbtbackActionPerformed

    private void jbtaddMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtaddMouseMoved
        // TODO add your handling code here:
          if(jbtadd.isEnabled()==true)
            jbtadd.setBackground(Color.YELLOW);
        else
            OriginalColor();
    }//GEN-LAST:event_jbtaddMouseMoved

    private void jbtdeleteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtdeleteMouseMoved
        // TODO add your handling code here:
          if(jbtdelete.isEnabled()==true)
            jbtdelete.setBackground(Color.YELLOW);
        else
            OriginalColor();
    }//GEN-LAST:event_jbtdeleteMouseMoved

    private void jbtsearchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtsearchMouseMoved
        // TODO add your handling code here:
          if(jbtsearch.isEnabled()==true)
            jbtsearch.setBackground(Color.YELLOW);
        else
            OriginalColor();
    }//GEN-LAST:event_jbtsearchMouseMoved

    private void jbtclearMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtclearMouseMoved
        // TODO add your handling code here:
          if(jbtclear.isEnabled()==true)
            jbtclear.setBackground(Color.YELLOW);
        else
            OriginalColor();
    }//GEN-LAST:event_jbtclearMouseMoved

    private void jbtexitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtexitMouseMoved
        // TODO add your handling code here:
          if(jbtexit.isEnabled()==true)
            jbtexit.setBackground(Color.YELLOW);
        else
            OriginalColor();
    }//GEN-LAST:event_jbtexitMouseMoved

    private void jbtbackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtbackMouseMoved
        // TODO add your handling code here:
          if(jbtback.isEnabled()==true)
            jbtback.setBackground(Color.ORANGE);
        else
            OriginalColor();
    }//GEN-LAST:event_jbtbackMouseMoved

    private void jbtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtupdateActionPerformed
        // TODO add your handling code here:
 try
        {
            int ModMe;
            ModMe = JOptionPane.showConfirmDialog(null, "Are you sure you want to Update this record?", "Modify?", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if(ModMe == JOptionPane.YES_OPTION)
            {
              DBconnection conn = new DBconnection();
                Connection connect = DBconnection.conn;
                Statement stmt = connect.createStatement();
                 stmt.executeUpdate("UPDATE data1 SET id ='" + txtid.getText() + "',Name ='" + txtname.getText() + "',Age ='" + txtage.getText() + "',Address ='" + txtadd.getText() + "',Gender ='" + txtgen.getSelectedItem() + "',Language ='" + txtlang.getText() + "',Number ='" + txtnum.getText() + "',Payment ='" + txtpay1.getText() +  "' Where id='" + txtid.getText() + "'");
               
                JOptionPane.showMessageDialog(null, "Update Record Successful.", "Modify", JOptionPane.INFORMATION_MESSAGE);
                
            connect.close();
            }
              
          }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    
 
        
    	

    }//GEN-LAST:event_jbtupdateActionPerformed

    private void jbtupdateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtupdateMouseMoved
        // TODO add your handling code here:
         if(jbtupdate.isEnabled()==true)
            jbtupdate.setBackground(Color.ORANGE);
        else
            OriginalColor();
    }//GEN-LAST:event_jbtupdateMouseMoved

private void jbtfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtfirstActionPerformed
// TODO add your handling code here:
    try{
         open();
        if(rs.first())
{
    setText();
}
}catch(Exception e){}
}//GEN-LAST:event_jbtfirstActionPerformed

private void jbtPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPreviousActionPerformed
// TODO add your handling code here:
    try{
         open();
if(rs.previous())
{
setText();setText();
}
}catch(Exception e){}
}//GEN-LAST:event_jbtPreviousActionPerformed

private void jbtnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnextActionPerformed
// TODO add your handling code here:
        try{
             open();
if(rs.next())
{
setText();
}
}catch(Exception e){}
}//GEN-LAST:event_jbtnextActionPerformed

private void jbtlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlastActionPerformed
// TODO add your handling code here:
            try{
                 open();
if(rs.last())
{
setText();
}
}catch(Exception e){}
}//GEN-LAST:event_jbtlastActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JOptionPane.showMessageDialog(null, "hai");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmPhoneBook().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtPrevious;
    private javax.swing.JButton jbtadd;
    private javax.swing.JButton jbtback;
    private javax.swing.JButton jbtclear;
    private javax.swing.JButton jbtdelete;
    private javax.swing.JButton jbtexit;
    private javax.swing.JButton jbtfirst;
    private javax.swing.JButton jbtlast;
    private javax.swing.JButton jbtnext;
    private javax.swing.JButton jbtsearch;
    private javax.swing.JButton jbtupdate;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtage;
    private javax.swing.JComboBox txtgen;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlang;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtpay1;
    // End of variables declaration//GEN-END:variables
public void open()
{
try
		{
			 DBconnection conn = new DBconnection();
            Connection connect = DBconnection.conn;
            Statement stmt = connect.createStatement();
            
			rs = stmt.executeQuery("Select * from data1");
                      
			if(rs.next())
			setText();
		}catch(Exception e){}

}
   
 public void setText() {
     
     try {
         
         txtid.setText(rs.getString(1));
        txtname.setText(rs.getString(2));
        txtage.setText(rs.getString(3));
        txtadd.setText(rs.getString(4));
        txtgen.setSelectedItem(rs.getString(5));
        txtlang.setText(rs.getString(6));
        txtnum.setText(rs.getString(7));
      
        txtpay1.setText(rs.getString(8));
}catch(Exception ex) {}



}
    private void center()
   {
      Dimension scr = Toolkit.getDefaultToolkit().getScreenSize();
      int       nX  = (int) (scr.getWidth()  - getWidth()  ) / 2;
      int       nY  = (int) (scr.getHeight() - getHeight() ) / 2;

      setLocation( nX, nY );
   }

 
        public void OriginalColor()
        {
          jbtadd.setBackground(Color.LIGHT_GRAY);
          jbtback.setBackground(Color.LIGHT_GRAY);
          jbtclear.setBackground(Color.LIGHT_GRAY);
          jbtdelete.setBackground(Color.LIGHT_GRAY);
           jbtexit.setBackground(Color.LIGHT_GRAY);
               jbtsearch.setBackground(Color.LIGHT_GRAY);
              
             
               
        }   

}
